# Generated by Django 2.2.16 on 2023-02-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
    ]
